print("Hello, Python World!")
print("\n")
print("Who uses Python?")
print("1. Software Engineers")
print("2. Mathematecians")
print("3. Data Analysts")
print("4. Scientists")
print("5. Accountants")
print("6. Network Engineers")
print("7. Kids")
print("8. Cyber Security Experts")
print("9. Web Developers")
print("\n")
print("Why do people use Python?")
print("1. It is easy to learn")
print("2. It is easy to read")
print("3. It is easy to write")
print("4. It is easy to maintain")
print("5. It is versatile")
print("6. It is powerful")
print("7. It is open-source")
print("8. It has a large community")
print("9. It has a large ecosystem")
print("10. It is cross-platform")
print("11. It is free")
print("12. It is object-oriented")
print("13. It is interpreted")
print("14. It is high-level")
print("15. It is dynamically typed")
print("16. It is extensible")
print("17. It is embeddable")